Repository orionalfa/node-moviedb-cli, pull requests merged in 2021-08, with the labels that each got.

#17 Feat/get person
  src/asciiPrompt.js
  src/chalk.js
  src/moviedb.js
  src/requests.js
Labels: enhancement

#18 Feat/get movies
  src/moviedb.js
  src/requests.js
Labels: enhancement

#25 Feat/adapted get movie
  src/moviedb.js
  src/requests.js
Labels: bug, enhancement

#26 Feat/save json files
  src/assets/img/app-view.png
  src/assets/js/asciiPrompt.js
  src/assets/js/chalk.js
  src/assets/js/helpers.js
  src/assets/postman/requests.json
  src/moviedb.js
  src/requests.js
Labels: enhancement

#32 Feat/render output
  src/assets/js/render.js
  src/moviedb.js
  src/requests.js
Labels: enhancement

#33 documentation: added README file
  README.md
Labels: documentation
